version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 18080:80
    volumes:
      - ./:/var/www/html
#      - /var/www/html
#    env_file:
#      - .env
